// <auto-generated />
using System;
using GrupoJuridico.Gestion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrupoJuridico.Gestion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("OrigenClienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoClienteId");

                    b.HasIndex("OrigenClienteId");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PersonaId", "Fecha");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Clave");

                    b.ToTable("ConfiguracionSistema", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.CorreoElectronico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("CorreosElectronicos", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.EstadoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("EstadosCliente", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.EstadoPrima", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("EstadosPrima", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Finca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("PersonaId");

                    b.ToTable("Fincas", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.MetodoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("MetodosVenta", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Numero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Numero");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Numeros", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.OrigenCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("OrigenesCliente", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Expediente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("Expediente");

                    b.HasIndex("VendedorId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.PersonaFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("PersonaFamiliares", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Prima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoPrimaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaEstimadaPago")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("MontoCancelado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPrimaId");

                    b.HasIndex("FechaEstimadaPago");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Primas", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.ProcedenciaVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("ProcedenciasVenta", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Vendedores", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MetodoVentaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcedenciaVentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetodoVentaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ProcedenciaVentaId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Infrastructure.Identity.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Infrastructure.Identity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.EstadoCliente", "EstadoCliente")
                        .WithMany()
                        .HasForeignKey("EstadoClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.OrigenCliente", "OrigenCliente")
                        .WithMany()
                        .HasForeignKey("OrigenClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCliente");

                    b.Navigation("OrigenCliente");
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Persona", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.CorreoElectronico", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Persona", null)
                        .WithMany("Correos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Finca", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Persona", null)
                        .WithMany("Fincas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Numero", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Persona", null)
                        .WithMany("Numeros")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Persona", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Cliente", "Cliente")
                        .WithOne("Persona")
                        .HasForeignKey("GrupoJuridico.Gestion.Domain.Entities.Persona", "ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.PersonaFamiliar", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Persona", null)
                        .WithMany("Familiares")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Prima", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.EstadoPrima", "EstadoPrima")
                        .WithMany()
                        .HasForeignKey("EstadoPrimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Venta", "Venta")
                        .WithOne("Prima")
                        .HasForeignKey("GrupoJuridico.Gestion.Domain.Entities.Prima", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoPrima");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Venta", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.MetodoVenta", "MetodoVenta")
                        .WithMany()
                        .HasForeignKey("MetodoVentaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.Persona", "Persona")
                        .WithMany("Ventas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrupoJuridico.Gestion.Domain.Entities.ProcedenciaVenta", "ProcedenciaVenta")
                        .WithMany()
                        .HasForeignKey("ProcedenciaVentaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MetodoVenta");

                    b.Navigation("Persona");

                    b.Navigation("ProcedenciaVenta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Infrastructure.Identity.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Infrastructure.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Infrastructure.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Infrastructure.Identity.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrupoJuridico.Gestion.Infrastructure.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GrupoJuridico.Gestion.Infrastructure.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Correos");

                    b.Navigation("Familiares");

                    b.Navigation("Fincas");

                    b.Navigation("Numeros");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("GrupoJuridico.Gestion.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Prima");
                });
#pragma warning restore 612, 618
        }
    }
}
